name: Sanity check translation phrases
on:
  push:
    branches:
      - main
    paths:
      - 'translations/**'
  pull_request:
    branches:
     - main
    paths:
      - 'translations/**'
  workflow_dispatch:
jobs:
  check_translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Setup Python 3.11
        with:
          python-version: "3.11"

      - name: Check translation phrases syntax
        working-directory: tools/language_check
        run: |
          python ./sanity_check.py

